image: python:3.10-bullseye      # Choose the image for running / в какой среде будет выполнятся

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - validate

default:      # Runs before any stage / выполняется перед каждой стадией
  cache:
    key:
      files:
        - requirements.txt
    paths:
      - .venv     # The directory where the commands will be executed / из какой директории будут выполнены команды
  before_script:
#    - export POSTGRES_HOST='db_ecodomskotom'; export POSTGRES_PORT='5432'; export POSTGRES_USER='pguser'
#    - export POSTGRES_PASSWORD='pgpass'; export POSTGRES_ENGINE='django.db.backends.postgresql_psycopg2'
#    - export DJANGO_ALLOWED_HOSTS='127.0.0.1 [::1] 0.0.0.0 localhost'; export SECRET_KEY='very_secret'; export DEBUG='0';
#    - export DJANGO_SETTINGS_MODULE='_project_.settings';
    - export DJANGO_ALLOWED_HOSTS='127.0.0.1 [::1] 0.0.0.0 localhost'
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip3 install --upgrade pip
    - pip3 install --upgrade setuptools
    - pip3 install -r requirements.txt

build-job:
  # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ls && uname -a        # Get info about system
    - echo $POSTGRES_PASSWORD
    - python3 manage.py migrate
    - python3 manage.py check

lint:
  stage: validate
  script:
    - prospector --profile-path . --profile .prospector.yaml .

test:
  # This job runs in the test stage.
  stage: test
  script:
    - pytest
