version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000  # внутри Докера запускается сервер на указанном порту
    volumes:
      - .//:/usr/src/ecodomskotom  # пока что установил туда же где и рабочая директория
    ports:
      - 7777:8000  # первая цифра - отвечает за порт на локальной машине
                   # вторая цифра указывает докеру какой порт слушать и передавать на локальный
    env_file:
      - ./.env.dev  # указываем где лежат скрытые переменные среды
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: