version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: db_ecodomskotom
    volumes:
      - ~/.pg/pg_data/ecodomskotom:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - custom

  web:
    image: ecodomskotom:latest
    container_name: ecodomskotom_project
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      bash -c "cd frontend && npm run dev" # frontend
    networks:
      - custom

networks:
    custom:
      driver: bridge
