# Generated by Django 3.2.6 on 2023-02-14 12:33

import core.historized.uided
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.UUIDField(default=core.historized.uided._new_uid, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('version', models.IntegerField(editable=False)),
                ('full_name', models.CharField(max_length=128, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=256, verbose_name='Почта')),
                ('message', models.TextField(max_length=1024, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
            bases=(core.models.AdminViewMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=core.historized.uided._new_uid, editable=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='updated')),
                ('version', models.IntegerField(editable=False)),
                ('full_name', models.CharField(max_length=128, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=256, verbose_name='Почта')),
                ('message', models.TextField(max_length=1024, verbose_name='Сообщение')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Контактная информация',
                'verbose_name_plural': 'historical Контактная информация',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
