# Generated by Django 3.2.6 on 2023-02-23 12:25

import core.historized.uided
import core.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('uid', models.UUIDField(default=core.historized.uided._new_uid, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated')),
                ('version', models.IntegerField(editable=False)),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('guest_number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество гостей')),
                ('comment', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Комментарий')),
                ('date', models.DateField(default=datetime.date(2023, 2, 23), verbose_name='Дата')),
                ('time_from', models.TimeField(choices=[(datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30')], verbose_name='Время от')),
                ('time_to', models.TimeField(choices=[(datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30')], verbose_name='Время до')),
                ('table_number', models.SmallIntegerField(choices=[(1, 'Стол №1'), (2, 'Стол №2'), (3, 'Стол №3'), (4, 'Стол №4'), (5, 'Стол №5'), (6, 'Стол №6'), (7, 'Стол №7'), (8, 'Стол №8'), (9, 'Стол №9'), (10, 'Стол №10'), (11, 'Стол №11'), (12, 'Стол №12')], verbose_name='Номер стола')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
            },
            bases=(core.models.AdminViewMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=core.historized.uided._new_uid, editable=False)),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='updated')),
                ('version', models.IntegerField(editable=False)),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('guest_number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество гостей')),
                ('comment', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Комментарий')),
                ('date', models.DateField(default=datetime.date(2023, 2, 23), verbose_name='Дата')),
                ('time_from', models.TimeField(choices=[(datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30')], verbose_name='Время от')),
                ('time_to', models.TimeField(choices=[(datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30')], verbose_name='Время до')),
                ('table_number', models.SmallIntegerField(choices=[(1, 'Стол №1'), (2, 'Стол №2'), (3, 'Стол №3'), (4, 'Стол №4'), (5, 'Стол №5'), (6, 'Стол №6'), (7, 'Стол №7'), (8, 'Стол №8'), (9, 'Стол №9'), (10, 'Стол №10'), (11, 'Стол №11'), (12, 'Стол №12')], verbose_name='Номер стола')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Бронирование',
                'verbose_name_plural': 'historical Бронирование',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
