# Generated by Django 3.2.6 on 2023-02-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20230223_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_from',
            field=models.TimeField(verbose_name='Время от'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_to',
            field=models.TimeField(verbose_name='Время до'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='time_from',
            field=models.TimeField(verbose_name='Время от'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='time_to',
            field=models.TimeField(verbose_name='Время до'),
        ),
    ]
